<h1>
Coeliac disease
</h1>
<p>
Coeliac disease is a genetically transmitted autoimmune disorder of the small intestine that occurs in those predisposed people of all ages from middle infancy onward. 
</p>
<p>
Symptoms include chronic diarrhoea, failure to thrive (in children) and fatigue, but these may be absent, and symptoms in other organ systems have been described.
</p>
<p>
Proper nutrition is essential in managing coeliac disease, and a nutritional consultation is highly recommended.
</p>
