<h1>
Nutrition for the elderly
</h1>
<p>
The elderly often have special dietary requirements. As we age, we typically require slightly less of some nutrients and more of others.  Diet can also play a part in helping to improve the quality of life of elderly people, as food is one of life's great pleasures, and as we get older we should be allowed to enjoy our food as much as we ever did.
</p>
<p>
A consultation with a dietitian will help you ensure that you or your elderly loved ones are being properly cared for in their nutritional needs.
</p>

