<h1>
Healthy Eating for Families
</h1>
<p>
Nutrition is an essential part of family life, and it is especially important to ensure that family members of all ages are eating the right foods in the right quantities to suit their needs. As babies and children develop, their nutritional needs change too. Certain foods that are correctly balanced in nutrients for young children are less beneficial for adults, and adults may have requirements that are not satisfied by these same foods.
</p>
<p>
It is therefore essential to be aware of the varied needs of all family members in order to provide a healthy diet for everyone.
</p>

