<h1>
  Information Links
</h1>
<p>
  The following links provide useful background information on nutrition and dietetics.
</p>
<ul>
  <li>
    <a href='http://www.bda.uk.com' target='_blank'>
      British Dietetic Association
    </a>
  </li>
  <li>
    <a href='http://www.hpc-uk.org' target='_blank'>
      Health Professions Council
    </a>
  </li>
  <li>
    <a href='http://www.nutrition.org.uk' target='_blank'>
      British Nutrition Foundation
    </a>
  </li>
  <li>
    <a href='http://www.food.gov.uk' target='_blank'>
      Food Standards Agency
    </a>
  </li>
  <li>
    <a href='http://www.bhf.org.uk' target='_blank'>
      British Heart Foundation
    </a>
  </li>
  <li>
    <a href='http://www.diabetes.org.uk' target='_blank'>
      Diabetes UK
    </a>
  </li>
  <li>
    <a href='http://www.coeliac.org.uk' target='_blank'>
      Coeliac Society
    </a>
  </li>
  <li>
    <a href='http://www.allergyuk.org' target='_blank'>
      The British Allergy Foundation
    </a>
  </li>
  <li>
    <a href='http://www.nhs.uk/change4life'>
      Change for Life
    </a>
  </li>
  <li>
    <a href='http://www.infantandtoddlerforum.org'>
      Infant and Toddler Forum
    </a>
  </li>
</ul>

