<h1>
  What are the differences between a dietitian and a nutritionist?
</h1>
<p>
  Nutritionists, unlike registered dietitians, do not have a protected name, so anyone may call themselves a nutritionist without having substantial scientific training. People can undergo short courses in nutrition and call themselves nutritionists while others do hold university degrees in nutrition or food science. Those that have completed a degree in nutrition are able to work in the public health sector but are not qualified to diagnose or treat health related nutrition problems, unlike dietitians.
</p>
<p>
  Many unqualified people call themselves 'nutritionists' to describe their involvement in food and nutrition related practice and therefore it is worth being extra cautious and checking what qualifications they hold when choosing a nutritionist.
</p>
<p>
  Please feel free to contact us if you have any other nutrition concerns that are not listed above. As part of the service, referrals to other specialities will be made if needed.
</p>

