<h1>
  Other services
</h1>
<p>
South East Nutrition and Health can provide health screening and blood test profiles and analyses. 
Following a consultation a test may be recommended to identify particular nutritional needs in detail. The available tests are listed below:
</p>
<h2> Mineral Profile </h2>
<ul>
  <li> Calcium </li>
  <li> Magnesium </li>
  <li> Zinc </li>
  <li> Iron </li>
  <li> Copper </li>
  <li> Chromium </li>
  <li> Manganese </li>
  <li> Selenium </li>
</ul>
<h2> Vitamin Profile </h2>
<ul>
  <li> Vitamin A, </li>
  <li> Vitamins B1, B2, B6, B12, </li>
  <li> Vitamin D(1,25 Dihydroxy), D(25 OH) </li>
</ul>
<h2> Well Person Profile </h2>
<ul>
  <li> Biochemistry Profile </li>
  <li> Haematology Profile </li>
  <li> Free T4 & TS </li>
  <li> Lipid Profile </li>
  <li> ESR </li>
</ul>
<h2> Well Man Profile </h2>
<ul>
  <li> Well Person profile </li>
  <li> PSA </li>
  <li> High Sensitivity CRP </li>
</ul>
<h2> Well Woman Profile </h2>
<ul>
  <li> Well Person Profile </li>
  <li> Iron Status </li>
  <li> High Sensitivity CRP </li>
</ul>
<h2> Cardiac Risk Profile </h2>
<ul>
  <li> Well Person Profile </li>
  <li> Lipoprotein </li>
  <li> High Sensitivity CRP </li>
  <li> Homocysteine </li>
  <li> Insulin </li>
</ul>
<h2> Iron Status </h2>
<ul>
  <li> Haematology Profile </li>
  <li> Serum Iron </li>
  <li> Ferritin </li>
  <li> TIBC (Total Iron Binding Capacity) </li>
</ul>
<h2> Lipid Profile </h2>
<ul>
  <li> Cholesterol </li>
  <li> Triglycerides </li>
  <li> High Density Lipoproteins (HDL) </li>
  <li> Low Density Lipoproteins (LDL) </li>
</ul>
<h2>
  Other services:
</h2>
<ul>
<li> Coeliac</li>
<li> Bone profile</li>
<li> Thyroid</li>
<li> Allergy</li>
<li> Semen analysis</li>
<li> Gut hormones</li>
<li> Folate</li>
<li> Glucose</li>
<li> HbA1c</li>
<li> Iodine</li>
<li> Lead</li>
<li> Mercury</li>
<li> Malarial Parasites</li>
<li> Om6/EPA Om3</li>
</ul>
