<h1>
PCOS - Polycystic Ovary Syndrome
</h1>
<p>
PCOS is a disease caused by hormone imbalance in women. Weight gain and difficulty in losing weight are common symptoms, as are irregular or no periods, facial hair, acne and infertility.
</p>
<p>
Insulin is a hormone made in the pancreas which helps the body use energy from food. Insulin resistance occurs when the body does not respond to normal levels of insulin and this results in more insulin production. High levels of insulin encourage the body to store fat which can lead to weight gain. As weight goes up, insulin resistance increases.  Insulin also promotes the production of testosterone in the body. Testosterone is often thought of as a male hormone but women need a small amount. However, having even slightly higher amounts can upset the balance of hormones in the body and lead to acne, excess hair and irregular periods. Irregular periods may result in infertility.  Long term health concerns associated with PCOS are linked to insulin resistance and include heart disease and diabetes.
</p>
<h3>Risk factors include:</h3>
<ul>
<li>
Altered levels of fats in the blood
</li>
<li>
High blood pressure
</li>
<li>
Being overweight and, in particular, having lots of fat around your middle.
</li>
</ul>
<p>
Many women with PCOS also suffer with insulin resistance, where the body resists the effects of insulin and so produces more to compensate. Continuously high insulin levels keep blood sugar levels low, which can prompt cravings for carbohydrate-rich foods. This causes the symptomatic weight gain.
</p>
<p>
Insulin resistance also increases the risk of longer-term health problems. Women with PCOS are, for example, seven times more likely to develop type 2 diabetes or have a heart attack. With correct diet, treatment and weight management, the risk of diabetes and heart attack can be reduced. Losing between 5% and 10% of excess body weight is enough to reduce the risk of diabetes and heart disease, and can improve fertility, and the other symptoms of PCOS.
</p>
<p>
A consultation with a dietitian will help you identify the most effective weight loss strategy for you, and therefore move you closer to coping with PCOS symptoms.
</p>


<h1>START NEW CONTENT HERE</h1>
<p>

It is estimated that 20 - 30% of women in the UK have polycystic ovaries, but only 10 - 15% have polycystic ovary syndrome (PCOS).Polycystic ovaries are often enlarged and contain many small cysts.
</p>
<p>
Symptoms of PCOS include:
</p>
<ul>

<li>
􀂄 Irregular or absent periods
</li>
<li>
􀂄 Excessive hair (hirsutism) particularly on the face, chest
or stomach
</li>
<li>
􀂄 Thinning of scalp hair or male-pattern baldness
</li>
<li>
􀂄 Acne
</li>
<li>
􀂄 Difficulty in maintaining a healthy body weight
</li>
<li>
􀂄 Fertility problems (difficulty conceiving)
</li>
</ul>
<p>
PCOS can be diagnosed by any combination of blood test results, an ultrasound scan or from a history of symptoms.  Sometimes the cysts may not be seen during a scan but a diagnosis can still be made using symptoms and blood test results.
</p>
<h2>
PCOS and insulin resistance
</h2>
<p>
Insulin is a hormone made in the pancreas which helps the body use energy from food. Insulin resistance occurs when the body does not respond to normal levels of insulin and this results in more insulin production. High levels of insulin encourage the body to store fat which can lead to weight gain. As weight goes up, insulin resistance increases. Insulin also promotes the production of testosterone in the body. Testosterone is often thought of as a male hormone but women need a small amount. However, having even slightly higher amounts can upset the balance of hormones in the body and lead to acne, excess hair and irregular periods. Irregular periods may result in infertility.  Long term health concerns associated with PCOS are linked to insulin resistance and include heart disease and diabetes.
</p>
<p>
Risk factors include:
</p>
<ul>
<li>
􀂄 Altered levels of fats in the blood
</li>
<li>
􀂄 High blood pressure
</li>
<li>
􀂄 Being overweight and, in particular, having lots of fat
around your middle.
</li>
</ul>
<p>

The symptoms of PCOS can be controlled using a combination of lifestyle changes, cosmetic measures and medication. Studies show that physical activity and weight loss are the most effective ways to improve insulin resistance and symptoms.
</p>
<h2>
What do you need to do with
your diet?
</h2>
<p>
It has been shown that even a 5% reduction in body weight can improve symptoms for overweight women with PCOS. The best way to lose weight is unclear and different things work for different people. Some women find slimming clubs helpful, some like to count calories or use meal replacements and others find cutting down portion sizes can help. The most important thing is finding something which suits your lifestyle without missing out on important foods.
</p>
<p>
For more information on healthy eating, check out the BDA factsheet titled 'Getting the balance right- a guide to healthy eating'.
</p>
What about carbohydrates?
Low carbohydrate diets and low glycaemic index (GI)
diets are often promoted for the treatment of PCOS.
Changing the amounts or type of carbohydrate you eat may
affect insulin levels. There is no
evidence that low carbohydrate diets
work in PCOS and nothing is known
about the long-term side effects.
Some women find that swapping some
high GI foods for low GI foods helpfultake
a look at the BDA factsheet titled
'Glycaemic index' for more information.
PCOS and the importance of
physical activity
There are many benefits to be gained from being
physically active but the most relevant to PCOS is that it
improves insulin resistance. There are lots of reasons why
some women struggle to increase their exercise levels
including finding the time and energy to do it. The most
important thing is to find something that you enjoy and can
fit into your lifestyle. Build it up gradually aiming to be active
for at least 30 minutes on most or all of the days of the week
for heart health but the recommendations for achieving
weight loss is 60 minutes per day. Remember that anything
which is more than usual for you, will be a great start.
Do you need to take
herbal supplements?
There are currently no good
quality studies which have shown
that herbal supplements such as
Agnus Castus and Saw Palmetto are
of benefit in PCOS.
Summary
􀂄 Diet and lifestyle is the most successful treatment for PCOS
in overweight women
􀂄 Even a 5% weight loss can improve symptoms and fertility
in overweight women
􀂄 This can be achieved by reducing energy intake and being
more active
Check out the BDA food factsheets on healthy eating and
glycaemic index at www.bda.uk.com
Sources of further information
Verity is a UK charity dedicated to providing support and
information to women diagnosed with PCOS. Details can be
found at www.pcos-org-uk.
PCOSUK is an organisation set up to provide information for
health professionals and further details can be found at
www.pcos-uk.org.uk.
This Food Fact sheet is a public service of The British Dietetic Association intended for information only.
It is not a substitute for proper medical diagnosis or dietary advice given by a dietitian.
To check that your dietitian is registered check www.hpc-uk.org.
Other Food Fact sheets are available from www.bda.uk.com
© BDA Written by Samantha Bailey, Angela Hargreaves and Pam Dyson, Dietitians, September 2007.
rust a dietitian
o know about nutrition T

</p>
