<h1>
  Why see a dietitian?
</h1>
<p>
  Dietitians are the only nutrition professionals to be statutorily regulated, and governed by an ethical code, to ensure that they always work to the highest standard.
</p>
<p>
  Dietitians are uniquely trained to take the most up to date public health and scientific research on food, health and disease, and translate this into practical guidance to enable you to make appropriate lifestyle and food choices.
</p>
<p>
  For more information on the British Dietetic Association please see www.bda.uk.com
</p>
<p>
  Registered Dietitians are the only qualified health professionals that assess, diagnose and treat diet and nutrition problems at an individual and wider public health level.
</p>
<p>
  Dietitians use the most up to date health and scientific research on food, health and disease and they translate the science of nutrition into practical guidance to inform and educate the general public about health and nutrition. They promote health and wellbeing through nutrition by teaching the public on how to make good food and lifestyle choices.
</p>
<p>
  Dietitians will have a 4 year Bachelor degree in Nutrition and Dietetics or a 3 year science degree followed by a master's degree in dietetics. Part of the degree will include completing a practical training element working in a hospital and in the community.
</p>
<p>
  Dietitians are the only nutrition professionals to be statutorily regulated, and governed by an ethical code which ensures that that they always work to the highest standard within the professional codes of conduct. The title dietitian can only be used by those appropriately trained professionals who have registered with the Health Professions Council.
</p>

