<h1>
Weight Loss
</h1>
<p>
Going on a diet to lose weight is an ever-popular activity, but do diets really work? Sometimes, yes, they can; however  maintaining a healthy weight requires understanding or your own particular dietary needs, (as well as work and dedication!) Following a weight-loss diet that doesn't accurately match your needs is difficult. It can also be ineffective, as weight can return as willpower wanes.
</p>
<p>
Our everyday diet is often habitual and based on learned behaviours. Successful and permanent weight loss may mean changing these behaviours, and simultaneously developing skills and strategies to deal with the changes.
</p>
<p>
We can help you understand all aspects of your weight management and help you achieve your goal to maintain a healthy, ideal weight.
</p>

