<h1>
Your Organisation
</h1>
<p>
The dietary needs within organisations are often overlooked, and as an employer or manager responsible for providing catering for staff you should consider the nutritional effects of your choices (or lack of them!)
</p>
<p>
There are many positive benefits to be gained from good quality nutrition in organisations. These may include improved morale, motivation and productivity, as well as reduced absence due to illness.
</p>
<p>
We can help you to create a sound nutritional basis for the provision of catering and nutrition within your organisation.
</p>
<p>
This can include dietetic services for individual employees or for the implementation of the government's public sector food procurement initiative (PSFPI).
</p>
<p>
We can also offer assistance in implementing national nutritional standards in schools and nurseries and other organisations ensuring compliance with current legislation. 
</p>


