<?php
include_once "debug.php";

$settings=array(
  'background'=>'3264be',
  'backgroundsubmenus'=>'3264be',
  'backgroundhover'=>'2d9bff',
  'backgroundsubmenushover'=>'2d9bff',
  'color'=>'eeeeee',
  'colorsubmenus'=>'eeeeee',
  'colorhover'=>'ffffff',
  'colorsubmenushover'=>'ffffff',
  'border'=>'000000',
  'bordersubmenus'=>'000000',
  'cols'=>4,
  'hidelogo'=>1,
  'hideimages'=>0,
  'hidetext'=>0,
  'border'=>0,
  'csv'=>0,
  'logo'=>true,
  'php5'=>1,
  'pass'=>"797c6024a632665af56e1de0d0b545ef"
);

$control=array(
  'generate_scripts'=>0,
  'generate_menu'=>1,
  'include_menu'=>1,
  'generate_tabs'=>1,
  'include_tabs'=>1,
  'generate_pages_xml'=>false,
  'generate_products_xml'=>false,
  'generate_sidebar_links'=>0,
  'include_sidebar_links'=>1,
	'show_right_sidebar_images'=>1,
	'body_styling'=>1
);

$scale=array(
  'itemw'=>6,
  'itemh'=>6,
  'listw'=>3,
  'listh'=>3,
  'adjust'=>array(
    '0'=>2,
    '0.0'=>4.0,
    '0.1'=>1,
    '0.2'=>2.5,
    '0.3'=>1.0,
    '0.4'=>2.00,
    '0.5'=>2.45
  ),
  'columns'=>array(
    '0'=>3,
    '0.0'=>2,
    '0.1'=>3,
    '0.2'=>4,
    '0.3'=>2,
    '0.4'=>5,
    '0.5'=>5,
    '1'=>2,
    '2'=>3
  )
  );
?>
