<h1>
About Us
</h1>
<p>
South East Nutrition and Health is a dietetic consultancy based in Guildford, Surrey.
</p>
<p>
SENH is owned and run by dietician Seamus Kirk BSc (Hons) RD HCIMA
</p>
<p>
After completing my practical training in several hospitals in Surrey I graduated from the University of Surrey with an Honours degree in nutrition and dietetics.
</p>
<p>
My posts have been within the community providing a dietetic service to over fifteen GP practices and several community hospitals.  This has provided both a very diverse and wide ranging experiences with patients at all levels covering areas such as diabetes, IBS, cholesterol, weight loss, oncology, nutrition support and various gastro and intestinal conditions.  Being aware of modern medical practice and medications is important in terms of diagnosis and providing effective dietary advice.
</p>
<p>
Prior to qualifying as a dietitian I founded London's first solely Fair Traded juice bar/caf&eacute; which specialised in organic food and drinks.  The unique concept gained exposure on BBC TV and local radio and in publications in London's Time Out and Evening Standard.
</p>
<p>
This practical background coupled with the community experience provide a solid and thorough understanding of all aspects of food and nutrition.
</p>
<p>
I look forward to working whether it be one to one or the larger audience and would welcome the opportunity to assist.
</p>
