<h1>
About Us
</h1>
<p>
South East Nutrition and Health is a dietetic consultancy based in Guildford, Surrey, founded by dietician <b>Seamus Kirk BSc (Hons) RD HCIMA</b>
</p>
<h2>Seamus:</h2>
<blockquote>
<p>
&quot;After completing my academic study in the Department of Nutrition and Dietetics, and practical training in several Surrey hospitals, I graduated from the University of Surrey with an Honours degree in Nutrition and Dietetics.
</p>
<p>
Recent posts have been within the community, providing dietetic services to over fifteen GP practices and several community hospitals. This has provided wide ranging experience with patients at all levels, covering areas such as diabetes, IBS, cholesterol, weight loss, oncology, nutrition support and various gastro-intestinal and intestinal conditions. My awareness of modern medical practice and medication is important in the diagnosis and provision of effective dietary advice, and exposure to a wide range of conditions has been a vitally important for my development and experience as a dietician.
</p>
<p>
Before qualifying as a dietitian I founded London's first fully organic juice bar and caf&eacute;, Coffee Matters. The company was run entirely on Fair Trade principles and gained exposure on BBC TV and local radio and received very favourable reviews in London's Time Out and Evening Standard.
</p>
<p>
My practical background combined with hands-on community experience in dietetics provides a deep and thorough understanding of all aspects of food and nutrition.
</p>
<p>
I welcome the opportunity to professionally assist with your dietary and nutrition requirements, and I look forward to working with you whether in a one-to-one setting or as part of a group.  &quot;
</p>
</blockquote>
<i>Seamus Kirk</>
