
<br/>
<br/>
<a target="_blank" href="http://www.bda.uk.com/"><img src="img/mbdaLogo.png" alt="Member British Dietetic Association" width="90" /></a>
<br/>
<br/>
<a target="_blank" href="http://www.hpc-uk.org/"><img src="img/hpc_logo.gif" alt="Health Professions Council" width="110" /></a>
<br/>
<br/>
<a target="_blank" href="http://www.hpcheck.org/"><img src="img/HPchecklogo.gif" alt="HP Check" width="130" /></a>
<br/>
