<h1>
  Locations
</h1>
<p>
  We run clinics at:
</p>
<h2>
  Appointment times
</h2>
<p>
  Appointments are available throughout the week. Clinics are typically run in the afternoon/ evening from 4pm- 8pm.
</p>
<p>
  It is also possible to have a consultation with us at other times, depending on availability. Please Contact us to discuss your individual requirements.
</p>
<h2>
  Insurance Cover
</h2>
<p>
  We are registered with major insurers. Please check with your insurance company as to what your policy covers you for.
</p>
<h2>
  Cancellation Policy
</h2>
<p>
  To enable us to run an efficient service with short waiting times, 24 hours notice is required to cancel an appointment. It is appreciated that in some circumstances, short notice may occasionally be unavoidable, and discretion will be exercised in such cases.
</p>
<p>
  We are registered with the
  <a target="_blank" href='www.hpcheck.org' name='www.hpcheck.org'>
    Health Professions Council (www.hpcheck.org)
  </a>
  and the
  <a target="_blank" href='www.bda.uk.com' name='www.bda.uk.com'>
    British Dietetic Association (www.bda.uk.com)
  </a>
</p>

