<h1>
Cancer
</h1>
<p>
Cancer and cancer treatments are often associated with nutritional problems. Your body must get the calories and nutrients it needs to maintain a healthy weight.
</p>
<p>
Cancer treatment places a high demand on the body. Nutrition support may help you maintain your body weight and meet your body's energy and nutrient requirements.</p>
<p>
A consultation with a dietician will help you ...
</p>

