<h1>
  What to expect from a consultation
</h1>
<p>
  A one to one consultation with us gives you the opportunity to discuss your individual needs and goals. We will ask you about your relevant medical and social history, your lifestyle and typical food choices and eating patterns. We firmly believe any changes to your diet and lifestyle have to be achievable and realistic if they are to work for you in the long term.
</p>
<p>
  Each consultation lasts up to an hour and comprises:
</p>
<ul>
  <li>
    Thorough assessment and scientifically sound nutritional advice tailored to suit you
  </li>
  <li>
    Formulation of a realistic action plan for change which you can achieve
  </li>
</ul>
<p>
  Although a one-off consultation might be all you feel you need, in most cases clients find further sessions invaluable. If so, you can then take advantage of a cost effective package of sessions. You can discuss your individual requirements with us at your first session.
</p>

