<h1>
Consultation
</h1>
<p>
A one to one consultation with us gives you the opportunity to discuss your individual dietary needs and goals. We will ask you about your relevant medical and social history, your lifestyle and typical food choices and eating patterns. Any changes to your diet and lifestyle have to be achievable and realistic if they are to work for you in the long term.
</p>
<p>
Each consultation lasts up to an hour and comprises:
</p>
<ul>
  <li>
    Discussion in confidence about your current diet, your history, your likes and dislikes, taking into account any medical concerns 
  </li>
  <li>
    Analysis of your dietary needs and the most sensible way to achieve benefits from changes to your diet
  </li>
  <li>
    A realistically achieveable action plan for change, if necessary, with follow up advice and monitoring
  </li>
</ul>
<p>
Although a single consultation may suffice, in many cases clients find additional consultation sessions invaluable in maintaining an improved nutritional balance. If you would like a series of consultations you can take advantage of a cost effective package of sessions. You can discuss your individual requirements with us at your initial consultation.
</p>

