<h1>
Food Allergy and Intolerance
</h1>
<p>
Allergic reactions and intolerance to certain foods can have an enormous impact on everyday life of those affected. In many cases sufferers are not aware that they are allergic to particular foods.
</p>
<p>
There is a great deal of information in the public domain related to food intolerance, much of it based on conjecture and heresay. We take a realistic attitude to the diagnosis and treatment of allergies and food intolerance, and base our recommendations on current scientific knowledge.
</p>
<p>
Food allergies and intolerances can be analysed and identified and then treated with the help of nutritional advice from a dietitian.
</p>

<h1>START NEW CONTENT HERE</h1>


<p>
How common is food allergy? It is estimated that about
3% of adults and 6-8% of children suffer from a food allergy
with 20% of the adult population 'thinking' that they have a
food intolerance.
Food Allergy
Food allergies occur when the
body’s immune system
inappropriately acts against a protein
within food-known as an allergen.
Antibodies are produced as part of
this response and a complex chain of
events occurs leading to the release
of substances such as histamine.
This histamine release causes the
symptoms of allergy such as
eczema, asthma, rhinitis,
conjunctivitis and in its most severe
form - life threatening anaphylaxis.
An allergic response to food always involves the immune
system and symptoms are frequently seen within minutes
although some allergic reactions can have delayed
symptoms. Due to the involvement of the immune system
there are some clear diagnostic tests that can be used in
conjunction with clinical history to diagnose a food allergy
e.g. Allergen specific IgE blood tests and Skin Prick Tests.
See the BDA website www.bda.uk.com Food Facts: "The
Truth about….food allergy and food intolerance testing" for
further details.
Food
Intolerance
An 'intolerance' to food
doesn't involve the immune
system, is rarely life
threatening and tends to
occur hours or days after the
food ingestion. A food
intolerance is an adverse
reaction to a food which
occurs when our body has
an inability to digest that food successfully. The most
common example being lactose intolerance where the body
doesn't produce sufficient lactase - the enzyme that
breakdowns lactose, the sugar found within milk.
Common food allergens:
􀂊 Cow's milk
􀂊 Eggs
􀂊 Shellfish
􀂊 Fish
􀂊 Soya
􀂊 Peanuts
􀂊 Wheat
􀂊 Tree nuts
These eight allergens account for about 90%
of all allergic reactions, however allergic
reaction to newer allergens such as sesame
and kiwi are becoming more common.
Food labelling:
Since November 2005
European Union (EU) legislation
has decreed that all pre-packaged
foods sold within the EU must be
labelled with the above 8 food
allergens as well as the following
four less common food allergens:
sesame, mustard, celery and
sulphites. By 23 December 2007
molluscs and lupin will also have to
be included.
</p>
<p>
Help and Advice
If you suspect that you have a food allergy or intolerance
seek medical advice from your GP and ask to see a
Registered Dietitian who will be able to help you with an
exclusion diet. If you would like to visit a private dietitian for
a consultation please visit www.dietitiansunlimited.co.uk to
search for a registered dietitian in your area.
-
</p>
<p>
This Food Fact sheet is a public service of The British Dietetic Association intended for information only.
It is not a substitute for proper medical diagnosis or dietary advice given by a dietitian.
To check that your dietitian is registered check www.hpc-uk.org.
Other Food Fact sheets are available from www.bda.uk.com
© BDA June 2007 - Written by Ruth Towell, Dietitian, on behalf of the BDA Food Allergy and Intolerance Specialist Group
rust a dietitian
To know about nutrition


</p>
