<h1>
Nutrition and Heart Health
</h1>
<p>
A healthy diet can help to protect you against heart disease. Good nutrition can play a significant part in reducing the main risk factors for heart disease: high cholesterol, overweight and high blood pressure.
</p>
<p>
 We can provide you with the latest evidence showing the links between diet and heart health, and we can have a closer look at your diet, and recommend changes that would help reduce your risk. 

This is an excellent time to consider what changes and additions to your diet could help to protect your heart health in the long term.
</p>

