<h1>
  Nutrition and Heart Health
</h1>
<p>
  A healthy diet can help to protect you against heart disease as your nutrition plays a significant part in helping to reduce the major risk factors for heart disease such as cholesterol, weight and high blood pressure (hypertension.)
</p>
<p>
  We can provide you with the latest evidence on links between diet and heart health and together you can take a closer look at your usual diet, and consider what changes would help to reduce your risk. It is also the ideal opportunity to consider what changes and additions to your diet could help to protect your heart health in the long term.
</p>

