<h1>
 IBS - Irritable Bowel Syndrome
</h1>
<p>
IBS is a bowel disorder characterized by abdominal pain, discomfort, bloating, and alteration of bowel habits. In some cases, symptoms are relieved by bowel movements. Symptoms include diarrhea, constipation, or both, alternating. IBS may begin after an infection, a stressful life event, or the onset of maturity.
</p>
<p>
Although there is no cure for IBS, there are treatments that can relieve symptoms. These include changes in diet, medication and psychological treatments.
</p>
<p>
Several conditions may present as IBS including coeliac disease, fructose malabsorption, mild infections, parasitic infections like giardiasis, several inflammatory bowel diseases, bile acid malabsorption, functional chronic constipation, and chronic functional abdominal pain. In IBS, routine clinical tests yield no abnormalities, although the bowels are often more sensitive to certain stimuli. The exact cause of IBS is unknown. The most common theory is that IBS is a disorder of the interaction between the brain and the gastrointestinal tract, although there may also be abnormalities in the gut flora or the immune system.
</p>
<p>
IBS does not lead to more serious conditions in most patients, however, it is a source of chronic pain, fatigue, and other symptoms and contributes to work absenteeism. Researchers have reported that the high prevalence of IBS, in conjunction with increased costs, produces a disease with a high social cost. It is also regarded as a chronic illness and can dramatically affect the quality of a sufferer's life.
</p>
