<h1>
 IBS - Irritable Bowel Syndrome
</h1>
<p>
Irritable bowel syndrome (IBS) is a functional bowel disorder characterized by chronic abdominal pain, discomfort, bloating, and alteration of bowel habits in the absence of any detectable organic cause. In some cases, the symptoms are relieved by bowel movements. Diarrhea or constipation may predominate, or they may alternate (classified as IBS-D, IBS-C or IBS-A respectively). IBS may begin after an infection (post-infectious, IBS-PI), a stressful life event, or the onset of maturity without any other medical indicators.
</p>
<p>
Although there is no cure for IBS, there are treatments that attempt to relieve symptoms, including dietary adjustments, medication and psychological interventions. Patient education and a good doctor-patient relationship are also important.
</p>
<p>
Several conditions may present as IBS including coeliac disease, fructose malabsorption, mild infections, parasitic infections like giardiasis, several inflammatory bowel diseases, bile acid malabsorption, functional chronic constipation, and chronic functional abdominal pain. In IBS, routine clinical tests yield no abnormalities, although the bowels may be more sensitive to certain stimuli, such as balloon insufflation testing. The exact cause of IBS is unknown. The most common theory is that IBS is a disorder of the interaction between the brain and the gastrointestinal tract, although there may also be abnormalities in the gut flora or the immune system.
</p>
<p>
IBS does not lead to more serious conditions in most patients, however, it is a source of chronic pain, fatigue, and other symptoms and contributes to work absenteeism. Researchers have reported that the high prevalence of IBS, in conjunction with increased costs, produces a disease with a high social cost. It is also regarded as a chronic illness and can dramatically affect the quality of a sufferer's life.
</p>
