<h1>
  Information Links
</h1>
<p>
  The following links provide useful background information on nutrition and dietetics.
</p>
<ul>
  <li>
    <a href='http://www.bda.uk.org'>
      British Dietetic Association
    </a>
  </li>
  <li>
    <a href='http://www.hpd-uk.org'>
      Health Professions Council
    </a>
  </li>
  <li>
    <a href='http://www.nutrition.org'>
      British Nutrition Foundation
    </a>
  </li>
  <li>
    <a href='http://www.food.gov.uk'>
      Food Standards Agency
    </a>
  </li>
  <li>
    <a href='http://www.bhf.org.uk'>
      British Heart Foundation
    </a>
  </li>
  <li>
    <a href='http://www.diabetes.org.uk'>
      Diabetes UK
    </a>
  </li>
  <li>
    <a href='http://www.coeliac.org.uk'>
      Coeliac Society
    </a>
  </li>
  <li>
    <a href='http://www.allergyuk.org'>
      The British Allergy Foundation
    </a>
  </li>
  <li>
    <a href='http://www.nhs.uk/change4life'>
      Change for Life
    </a>
  </li>
  <li>
    <a href='http://www.infantandtoddlerforum.org'>
      Infant and Toddler Forum
    </a>
  </li>
</ul>

