<h1>
Insurance providers
</h1>

<p>
  We are officially recognised by the following healthcare medical insurance providers:
</p>
<ul>
  <li>
    PPP Healthcare Insurance
  </li>
  <li>
    Western Provident Association
  </li>
</ul>
<p>
  This list is certainly not exhaustive and there are instances where other insurers cover consultations. Please feel free to enquire or ask your insurer direct.
</p>
<p>
  Many insurance providers will cover the cost of a new and follow-up appointment with a Registered Dietitian if the original referral has been received from a Consultant.
</p>
<ul>
  <li>
    Health Questionnaire.pdf
  </li>
  <li>
    3 Day Food Diary.pdf
  </li>
  <li>
    Food and Symptom Diary.pdf
  </li>
</ul>

