<h1>
Lethargy and loss of vitality
</h1>
<p>
Chronic lethargy and loss of vitality can sometimes be related to nutrition. This is especially true in cases where an allergy or food intolerance has gone unnoticed, or when there is a medical condition present that has been un-diagnosed or untreated.
</p>
<p>
Correct and appropriate diet can help play a part in improving vitality and energy levels.
</p>
<p>
A consultation with a dietitian will help you to identify any possible dietary reasons for your condition, and may help you regain your exuberance and full energy levels.
</p>

