<h1>
  Contacting your GP
</h1>
<p>
  In some cases, it might be necessary to contact your GP prior to your consultation for more information. However, your permission will always be granted before contacting anyone else with regards your treatment.
</p>
<p>
  For example if you have a newly diagnosed condition, a complex medical history, or details of blood test results or medication are required, prior to giving advice.
</p>

