Other services

Health screening profiles

Mineral Profile
•	Calcium, Magnesium, Zinc, Iron , Copper, Chromium, Manganese, Selenium

Vitamin Profile
•	Vitamin A, B1,B2,B6, B12, D(1,25 Dihydroxy), D(25 OH)….B12???

Well Person Profile
•	Biochemistry Profile
•	Haematology Profile
•	Free T4 & TS
•	Lipid Profile
•	ESR

Well Man Profile
•	Well Person profile
•	PSA
•	High Sensitivity CRP

     Well Woman Profile
•	Well Person Profile
•	Iron Status
•	High Sensitivity CRP


Cardiac Risk Profile
•	Well Person Profile
•	Lipoprotein
•	High Sensitivity CRP
•	Homocysteine
•	Insulin

Iron Staus
•	Haematology Profile
•	Serum Iron
•	Ferritin
•	TIBC (Total Iron Binding Capacity)

Lipid Profile
•	Cholesterol
•	Triglycerides
•	High Density Lipoproteins (HDL)
•	Low Density Lipoproteins (LDL)

Other services: Coeliac, Bone profile, Semen analysis, Thyroid, Allergy, Gut hormones, Folate, Glucose, HbA1c, Iodine, Lead, Mercury, Malarial Parasites, Om6/EPA Om3,

