<h1>
  Other services
</h1>
<h2>
  Health screening profiles
</h2>
<h2>
  Mineral Profile
</h2>
<ul>
  <li>
    Calcium
  </li>
  <li>
    Magnesium
  </li>
  <li>
    Zinc
  </li>
  <li>
    Iron
  </li>
  <li>
    Copper
  </li>
  <li>
    Chromium
  </li>
  <li>
    Manganese
  </li>
  <li>
    Selenium
  </li>
</ul>
<h2>
  Vitamin Profile
</h2>
<ul>
  <li>
    Vitamin A,
  </li>
  <li>
    Vitamins B1, B2, B6, B12,
  </li>
  <li>
    Vitamin D(1,25 Dihydroxy), D(25 OH)
  </li>
</ul>
<h2>
  Well Person Profile
</h2>
<ul>
  <li>
    Biochemistry Profile
  </li>
  <li>
    Haematology Profile
  </li>
  <li>
    Free T4 & TS
  </li>
  <li>
    Lipid Profile
  </li>
  <li>
    ESR
  </li>
</ul>
<h2>
  Well Man Profile
</h2>
<ul>
  <li>
    Well Person profile
  </li>
  <li>
    PSA
  </li>
  <li>
    High Sensitivity CRP
  </li>
</ul>
<h2>
  Well Woman Profile
</h2>
<ul>
  <li>
    Well Person Profile
  </li>
  <li>
    Iron Status
  </li>
  <li>
    High Sensitivity CRP
  </li>
</ul>
<h2>
  Cardiac Risk Profile
</h2>
<ul>
  <li>
    Well Person Profile
  </li>
  <li>
    Lipoprotein
  </li>
  <li>
    High Sensitivity CRP
  </li>
  <li>
    Homocysteine
  </li>
  <li>
    Insulin
  </li>
</ul>
<h2>
  Iron Status
</h2>
<ul>
  <li>
    Haematology Profile
  </li>
  <li>
    Serum Iron
  </li>
  <li>
    Ferritin
  </li>
  <li>
    TIBC (Total Iron Binding Capacity)
  </li>
</ul>
<h2>
  Lipid Profile
</h2>
<ul>
  <li>
    Cholesterol
  </li>
  <li>
    Triglycerides
  </li>
  <li>
    High Density Lipoproteins (HDL)
  </li>
  <li>
    Low Density Lipoproteins (LDL)
  </li>
</ul>
<h2>
  Other services:
</h2>
<p>
  Coeliac, Bone profile, Semen analysis, Thyroid, Allergy, Gut hormones, Folate, Glucose, HbA1c, Iodine, Lead, Mercury, Malarial Parasites, Om6/EPA Om3,
</p>
