<h1>
South East Nutrition and Health
</h1>
<p>
South East Nutrition and Health seeks to inspire healthy, balanced living through good diet. 
</p>
<p>
South East Nutrition and Health, founded by <a href="http://www.hpcheck.org">Health Professions Council registered dietician</a> <b>Seamus Kirk, BSc. (Hons) RD HCIMA</b> is passionate about the benefits of nutrition, and the changes good dietary practice can bring.
<p>

Diet choices face us every day and are informed by our cultural background, national heritage and socio-economic environment, as well as, for example, our personal development, our tendency to be experimental or conservative in our choices, and even our experiences of travel! They are also informed by our personal beliefs and knowledge about food and, importantly, by what we read or hear in the media and in the news.
</p>
<p>
Many of the choices we make may be less than optimal for our health; most of us know that too much fat, salt or alcohol, for example, can be harmful, but there are many foods that contain much more fat or salt or sugar than most people realise. There may be other foods that, together, or over the course of time, can constitute an unhealthy diet for us as individuals. Or it may be that beneficial foods are being omitted from your normal diet.
</p>
<p>
With food and health so often in the media spotlight, it can be a challenge to know what is best for you. 
</p>

<p>
South East Nutrition and Health provides a full dietetic service to individuals and organisations to help them attain a balanced, healthy diet. This service works through a process of consultation, analysis and recommendations based on a study of the best options for dietary improvement in each case.
</p>

<p>
South East Nutrition and Health are committed to a high level of professionalism and quality and all our work is based on current scientific research and knowledge in order to provide the best possible dietary advice and recommendations.
</p>

<p>
Please use the links on this page to find out more about our service.
</p>
