<h1>
South East Nutrition and Health
</h1>
<p>
South East Nutrition and Health seeks to inspire healthy, balanced living through good diet. 
</p>
<p>
South East Nutrition and Health was founded by <b>Seamus Kirk, BSc. (Hons) RD HCIMA</b>. Seamus is a <a href="http://www.hpcheck.org">Health Professions Council (HPC) registered dietician</a>, and is passionate about the benefits of nutrition, and the changes good dietary practice can bring.
<p>

Diet choices face us every day and are informed by our likes and dislikes, our cultural background, national heritage and socio-economic environment, as well as, for example, our upbringing and development, or our experiences of travel, our tendency to be experimental or conservative in our choices. They are also informed by our personal beliefs about food and, importantly, on what we read or hear in the media and in the news.
</p>
<p>
Many of the choices we make may be less than optimal for our health; we all know that too much fat, or salt, or alcohol can have harmful effects, but there may be many other dietary conditions that, together, or over the course of time, can constitute an unhealthy diet for us as individuals.
</p>
<p>
With food and health so often in the media spotlight, it can be a challenge to know what is best for you. 
</p>

<p>
South East Nutrition and Health provides a full dietetic service to individuals and organisations to help them attain a better diet. This service works through a process of consultation, analysis and recommendations based on a study of the best options for dietary improvement in each case.
</p>

<p>
South East Nutrition and Health are committed to a high level of professionalism and quality and we base all our work on current scientific research and knowledge in order to provide the best possible dietary advice and recommendations.
</p>
