<h1>
Overview of Dietetics
</h1>

<p>
"A dietitian is a health care professional who focuses on proper food and nutrition in order to promote good health." 
(reference: <a target="_blank" href="http://en.wikipedia.org/wiki/Dietetics">http://en.wikipedia.org/wiki/Dietetics</a>).
</p>
<p>
Dietetics is the professional practice that matches current scientific knowledge about diet to the practical requirements of food and nutrition.
</p>

<p>
Dietetic professionals are the only nutrition professionals to be regulated by statute, and they are governed by a code of ethics to ensure they always work to the highest standard and within professional codes of conduct.
</p>
<p>
Dietitians are specifically trained to apply the most up-to-date public health and scientific research on food, health and disease, and translate this into practical guidance to enable you to make appropriate lifestyle and food choices.
</p>
<p>
For more information on the British Dietetic Association please see <a target="_blank" href="http://www.bda.uk.com">bda.uk.com</a>.
</p>
<p>
Registered Dietitians are the only qualified health professionals that assess, diagnose and treat diet and nutrition problems at an individual level and the wider public health level.
</p>
<p>
Dietitians normally qualify with a 4 year Batchelor of Science degree (BSc.) in Nutrition and Dietetics or a 3 year BSc. followed by a Master's degree (MSc.) in Dietetics. These courses typically include practical training working in a hospital and in the community.
</p>
<p>
The title "Dietitian" can only be used by qualified dieticians who are registered with the Health Professions Council. Please refer to the <a target="_blank" href="http://www.hpcheck.org.uk">HPC website</a> for further information.
</p>

