<h1>
  Packages
</h1>
<h2>
  Starter Package
</h2>
<p>
  A starter package is ideal for anyone wanting to achieve nutrition or lifestyle improvements.
</p>
<p>
  It comprises:
</p>
<ul>
  <li>
    A total of 3 hours of one on one time with us
  </li>
  <li>
    Scientifically based nutrition and lifestyle advice tailored to help you reach your goals
  </li>
  <li>
    Meal ideas and plans to fit in with your lifestyle
  </li>
  <li>
    A problem solving approach to help you overcome any difficulties
  </li>
  <li>
    Support, advice and motivational techniques to keep you on track
  </li>
</ul>
<h2>
  Intensive Package
</h2>
<p>
  This provides longer term follow up, support and motivation for those goals which might be a little harder to reach:
</p>
<ul>
  <li>
    All of the above in addition to:
  </li>
  <li>
    A total of 5 hours of one on one time with us
  </li>
  <li>
    Unlimited phone or email contact between sessions
  </li>
</ul>
<h2>
  Nutrition and fitness packages
</h2>
<p>
  We can work alongside fitness specialists who specialise in helping you improve your physical well being. Combined intervention from both a nutrition and fitness professional can give you the edge on meeting your goals.
</p>

