<h1>
  Packages
</h1>
<h2>
  Standard services
</h2>
<table class="packages">
<thead>
<tr>
<th>Service</th>
<th>Price</th
</thead>
</tr>
<tbody>
<tr>
<td>
Initial phone consultation (10 minutes)
</td>
<td>
FREE
</td>
</tr>
<tr>
<td>
Initial consultation (1 hour)
</td>
<td>
&pound;75
</td>
</tr>
<tr>
<td>
Follow-up appointments (per 15 minutes)
</td>
<td>
&pound;20
</td>
</tr>
<tr>
<td>
Dietary analysis with full report 
</td>
<td>
&pound;95
</td>
</tr>
</tbody>
</table>


<h2>Packages</h2>
<table class="packages">
<thead>
<tr>
<th>Package</th>
<th>Description</th>
<th>Price</th>
</thead>
</tr>
<tbody>
<tr>
<td> Appointment Plus </td>
<td> Initial appointment plus 30 minute follow up </td>
<td> &pound;105 </td>
</tr>
<tr>
<td> Starter </td>
<td> 
 A starter package is ideal for anyone wanting to achieve nutrition or lifestyle improvements. It comprises:
    <ul>
      <li>A total of 3 hours of one-on-one time with us</li>
      <li>Nutrition and lifestyle advice to help you reach your goals</li>
      <li>Meal ideas and plans to fit in with your lifestyle</li>
      <li>A problem-solving approach to help you overcome any difficulties</li>
      <li>Support, advice and motivational techniques to keep you on track</li>
    </ul>
</td>
<td> &pound;200 </td>
</tr>
<tr>
<td>Weight loss </td>
<td> Initial appointment plus 30 minute follow up and two 15 minute follow-up sessions </td>
<td> &pound;125 </td>
</tr>
<tr>
<td>Follow up </td>
<td>Pay for 3 and get 4th free </td>
<td> &pound;60 </td>
</tr>
</tbody>
</table>

<p>
Packages include a discount when booked and purchased together.
</p>
<p>
Fees may vary dependent on location and packages. All fees are in line with the British Dietetic Association standards and recommendations.
</p>
