<h1>
PCOS - Polycystic Ovary Syndrome
</h1>
<p>
PCOS is a disease that only occurs in women, and is caused by hormone imbalance. Weight gain and difficulty in losing weight are common symptoms, as are irregular or no periods, facial hair, acne and infertility.
</p>
<p>
Many women with PCOS also suffer with insulin resistance, where the body resists the effects of insulin and so produces more to compensate. Continuously high insulin levels keep blood sugar levels low, which can prompt cravings for carbohydrate-rich foods. This causes the symptomatic weight gain.
</p>
<p>
Insulin resistance also increases the risk of longer-term health problems. Women with PCOS are, for example, seven times more likely to develop type 2 diabetes or have a heart attack. With correct diet, treatment and weight management, the risk of diabetes and heart attack can be reduced. Losing between 5% and 10% of excess body weight is enough to reduce the risk of diabetes and heart disease, and can improve fertility, and the other symptoms of PCOS.
</p>
<p>
A consultation with a dietician will help you identify the most effective weight loss strategy for you, and therefore move you closer to coping with PCOS symptoms.
</p>

