<h1>
PCOS - Polycystic Ovary Syndrome
</h1>
<p>
PCOS is a disease caused by hormone imbalance in women. Weight gain and difficulty in losing weight are common symptoms, as are irregular or no periods, facial hair, acne and infertility.
</p>
<p>
Insulin is a hormone made in the pancreas which helps the body use energy from food. Insulin resistance occurs when the body does not respond to normal levels of insulin and this results in more insulin production. High levels of insulin encourage the body to store fat which can lead to weight gain. As weight goes up, insulin resistance increases.  Insulin also promotes the production of testosterone in the body. Testosterone is often thought of as a male hormone but women need a small amount. However, having even slightly higher amounts can upset the balance of hormones in the body and lead to acne, excess hair and irregular periods. Irregular periods may result in infertility.  Long term health concerns associated with PCOS are linked to insulin resistance and include heart disease and diabetes.
</p>
<h3>Risk factors include:</h3>
<ul>
<li>
Altered levels of fats in the blood
</li>
<li>
High blood pressure
</li>
<li>
Being overweight and, in particular, having lots of fat around your middle.
</li>
</ul>
<p>
Many women with PCOS also suffer with insulin resistance, where the body resists the effects of insulin and so produces more to compensate. Continuously high insulin levels keep blood sugar levels low, which can prompt cravings for carbohydrate-rich foods. This causes the symptomatic weight gain.
</p>
<p>
Insulin resistance also increases the risk of longer-term health problems. Women with PCOS are, for example, seven times more likely to develop type 2 diabetes or have a heart attack. With correct diet, treatment and weight management, the risk of diabetes and heart attack can be reduced. Losing between 5% and 10% of excess body weight is enough to reduce the risk of diabetes and heart disease, and can improve fertility, and the other symptoms of PCOS.
</p>
<p>
A consultation with a dietician will help you identify the most effective weight loss strategy for you, and therefore move you closer to coping with PCOS symptoms.
</p>

