<h1>
PCOS - Poly-Cystic Ovary Syndrome
</h1>
<p>
PCOS is caused by an imbalance in hormones and weight gain and difficulty in losing it are common symptoms, as are irregular or no periods, facial hair, acne and infertility.
</p>
<p>
Many women with PCOS also suffer with insulin resistance, where the body resists the effects of insulin and so produces more to compensate. These continuously high insulin levels keep blood sugar levels low, which in turn often prompts cravings for sugary carbohydrate-rich foods. Unfortunately, this may mean weight gain and difficulty losing weight again.
</p>
<p>
Insulin resistance also increases the risk of longer-term health problems. Women with PCOS are seven times more likely to develop type 2 diabetes or have a heart attack for example. With correct treatment and weight management, risks such as diabetes and heart attack can be reduced. Losing between 5% and 10% of excess body weight is enough to reduce the risk of getting diabetes and heart disease, improve fertility and can make a big difference to symptoms.
</p>
<p>
A consultation with a dietician will help you ...
</p>

