<h1>
  Our Philosophy
</h1>
<p>
  We are passionate about educating, motivating and inspiring people to lead healthy, balanced lives. She has extensive experience in helping people with the challenges faced when changing eating and lifestyle behaviour.
</p>
<p>
  We understands that everyone&apos;s needs are different, whether it be a thirst for knowledge on diet and nutrition or a more supportive, skill based approach to changing behaviour, a dietetic consultation with us can help.
</p>
<p>
  With food and health constantly in the media spotlight, it can often feel a challenge to know what is best for you. We are committed to communicating clear, sound, nutrition information to the public. She has recently appeared on the BBC Breakfast programme to discuss and debate topics such as &apos;superfoods&apos; and &apos;taxing chocolate!&apos; and also contributes to main stream press.
</p>

