<h1>
  Type 2 Diabetes
</h1>
<p>
  You may have just been diagnosed with type 2 diabetes or had it for some time. Diabetes is a chronic condition, although it can't be cured, it can be treated very successfully.
</p>
<p>
  The ideal aim of treatment is to achieve blood glucose, blood pressure and cholesterol levels as near to normal as possible. This, together with a healthy lifestyle, will help to improve your wellbeing and protect against long-term damage to the eyes, kidneys, nerves, heart and major arteries. What you eat, how much activity you do and what your weight is are therefore central to your treatment for diabetes. We can look at all these factors with you and help you to work out a plan to suit you.
</p>
<p>
  You may be taking tablets and/or insulin to help you achieve normal blood glucose levels. Information from your medical practitioner on your medical treatment and medication would be needed, prior to your consultation.
</p>

