<h1>
Type 2 Diabetes
</h1>
<p>
Diabetes is a chronic condition, and although it can't be "cured", it can be treated very successfully.
You may have just been diagnosed with type 2 diabetes or had it for some time. In either case a dietary consultation can be of benefit.
</p>
<p>
The ideal aim of treatment is to achieve blood glucose, blood pressure and cholesterol levels as near to normal as possible. This, together with a healthy lifestyle, will help to improve your wellbeing and protect against long-term damage to the eyes, kidneys, nerves, heart and major arteries. What you eat, how much activity you do and what your weight is are therefore central to your treatment for diabetes. We can look at all these factors with you and help you to work out a plan to suit you.
</p>
<p>
You may be taking prescibed medication and/or insulin to help you achieve normal blood glucose levels. Information from your medical practitioner on your medical treatment and medication would be needed prior to a consultation.
</p>

<h1>START NEW CONTENT HERE</h1>

<p>
Diabetes is a condition in which the amount of glucose
(sugar) in the bloodstream is too high because the body
cannot control it properly.
The blood glucose level is normally kept in range by a
hormone called insulin, which is produced from the
pancreas. Insulin controls blood glucose levels by
allowing glucose to enter the cells so it can be used as
fuel by the body. In people with diabetes there is either
not enough insulin being produced, or it does not work
properly.
There are two main types of diabetes, and the
approach to food may vary depending on the type of
diabetes and the treatment being followed.
􀂊 Type 1 diabetes occurs when the body is unable to
produce any insulin and this has to be replaced, usually
through insulin injections.
􀂊 Type 2 diabetes is when the body is able to make
some insulin but not enough, or when the insulin
produced does not work properly (called 'insulin
resistance').
The aim for both types of diabetes is to achieve and
maintain the best possible control of blood glucose, blood
pressure and cholesterol; which will reduce your risk of
diabetes complications in the future. What you eat or
don't eat and your physical activity level are vital in
controlling all these factors, but that does not mean that
you should not still enjoy your food and the occasional
'treat'!
All people with diabetes
should have access to a
dietitian at diagnosis, either
through structured patient
education in groups or as an
individual consultation. You
may ask your GP to refer you
to a dietitian at any time but
this is often useful at times
when changes are being
made to your diabetes
treatment.
This fact sheet will give
you simple information about healthy food choices
suitable for everybody, including adults with diabetes. The
national diabetes charity, Diabetes UK, produces more
comprehensive information available both online and in
print (see www.diabetes.org.uk or call the Careline on
0845 120 2960 for more details). The full range of Food
Facts produced by the British Dietetic Association
complements the information in this fact sheet and for
more details about healthy eating, visit the Food
Standards Agency web site at www.eatwell.gov.uk
Type 1 diabetes
If you have Type 1 diabetes, you should see a dietitian
who will help you to understand the balance between the
carbohydrate you eat and your insulin doses. This will
help you to manage your diabetes more effectively.
You will also reduce your risk
of long term health problems if
you follow some of the key
points highlighted for people
with type 2 diabetes.
Type 2 diabetes
Being aware of carbohydrate
foods and food portion sizes is
important if you have Type 2 diabetes. The following
general guidelines will help to manage your diabetes and
benefit your general health:
􀂊 Eat regularly - aim for three meals a day, including
breakfast
􀂊 Include some carbohydrate foods with a lower
glycaemic index at each meal
􀂊 Aim for at least 5-a-day: that's portions of fruits and
vegetables
􀂊 Eat oily fish such as mackerel, sardines or salmon
twice a week
􀂊 Eat fewer sugary foods and drinks
􀂊 Eat fewer fatty foods, particularly saturated fats
􀂊 Eat less salt and salty foods.
Eat regularly
Aim for healthy balanced meals based around the
Balance of Good Health. See the BDA fact sheet 'Getting
the Balance Right - A Guide to Healthy Eating' for more
information. Include some 'starchy' carbohydrate foods at
each meal, such as bread, potatoes, rice, pasta, or
chapatti. The larger the portion, the more effect these
foods will have on raising blood glucose. Wholegrain
starchy foods may help to control your blood glucose.
These have a lower 'Glycaemic Index' (G.I.), which
helps you to feel full longer, reduce rapid rises & falls in
blood glucose and so should be chosen more often.
Examples of lower G.I. carbohydrate foods include
wholegrain bread, porridge oats, pulses, most fruit and
low fat yogurt.
Weight
Excess weight, in particular around your waist, can
make your diabetes harder to control. Losing weight can
be difficult but evidence shows that even a small weight
loss of just 5-10% of your body weight can bring
significant health benefits. Losing weight gradually, about
½ to 1kg (1-2lb) per week is the most effective. You may
also need advice about adjustments to your medication if
you are making significant changes to your diet and
physical activity level.
Fruits & Vegetables
Eating more fruits and
vegetables will lower your risk of heart
disease, strokes and some cancers.
Contrary to popular belief, people with
diabetes can eat all types of fruit, but
eating large quantities, for example several portions at
once, will raise blood glucose. That's why it's useful to
know what counts as one portion:
􀂊 One piece of ordinary sized fruit, e.g. apple, orange,
banana
􀂊 Two small fruits, e.g. plums or satsumas
􀂊 A handful of grapes or a slice of a large fruit, e.g.
melon
􀂊 ½ - 1 tablespoon of dried fruit, e.g. sultanas
􀂊 A small glass of pure fruit juice (150ml)
􀂊 2-3 tablespoon of cooked vegetables or a small bowl of
mixed salad.
Oily Fish
The Omega-3 fats found in oily fish may have several
health benefits but in particular eating more oily fish can
protect your heart, so it's recommended people with
diabetes eat one or two portions each week. Examples of
oily fish include mackerel, sardines, salmon, trout and
herring. Fish oil supplements are not generally
recommended but speak to your doctor or dietitian for
personalised advice.
Sugar
It's not necessary to follow a sugar-free diet, nor would
it be possible to. Choose lower sugar or reduced-sugar
foods where possible. The amount of sugar in savoury
foods is not usually significant. Artificial sweeteners can
be useful for people with diabetes, especially if trying to
lose weight
Fats
Fat is extremely high in calories so eating less fat and
fatty foods will help you lose weight. Saturated fats, such
as those found in pastry, butter, fatty meat and high-fat
dairy foods like cheese, are linked to heart disease so
reduce this type of fat as much as possible. Replace it
with leaner and reduced fat versions, and with monounsaturated
fats such as rapeseed oil, pure vegetable oil,
olive oil and spreads made from these.
Salt
It's recommended that we have
less than 6g of salt per day. Prepackaged
and convenience foods
contain a lot of salt, so a simple way to
reduce your salt intake is to include
more fresh food and 'home cooking' in
your diet. Lowering your salt intake will
help to improve your blood pressure and reduce your risk
of heart disease, strokes and some cancers.
Alcohol
There's generally no reason
why people with diabetes should
not drink alcohol, unless you have
been advised not to, but it is
important to stick to the safe limits.
That's up to two units per day for
women and up to three units per
day for men. A small glass of wine
(125ml) is usually about 1½ units,
while a pint of ordinary strength
(3.5%) beer is roughly two units.
Single pub measures (25ml) of spirits are also one unit.
Alcohol is high in calories, so if you're trying to lose weight
it can be helpful to reduce your intake of alcoholic drinks.
'Diabetic' Foods
Foods labelled as 'diabetic', such as sweets, cakes and
chocolates, offer no special benefits and are not
recommended. They may be high in fat and calories, are
expensive and some may cause diarrhoea.
Physical Activity
Aim for at least 30
minutes of moderate physical
activity on five days of the
week. 'Moderate' means
breathing more deeply and
feeling warmer, e.g. walking,
gardening, housework etc.
This Food Fact sheet is a public service of The British Dietetic Association intended for information only.
It is not a substitute for proper medical diagnosis or dietary advice given by a dietitian.
To check that your dietitian is registered check www.hpc-uk.org.
Other Food Fact sheets are available from www.bda.uk.com
© BDA November 2007
Written by Paul McArdle, Dietitian, on behalf of the BDA Diabetes Management and Education Group (DMEG)
rust a dietitian
o know about nutrition T

</p>
