<h1>
Vegetarian and Vegan Nutrition
</h1>
<p>
Vegetarian and vegan diets are healthy and nutritious and delicious, however as any vegetarian or vegan knows it is important to have an understanding of the particular types of foods that are essential in order to achieve a balanced diet. 
</p>
<p>
Non-vegetarians meet most of their protein needs through the consumption of meat or fish, whereas vegetarians and vegans must source their protein from good vegetable sources such as beans and peas and lentils (pulses) and grain-based foods such as bread.
</p>

