<h1>
  Weight Management
</h1>
<p>
  Many people diet to shed extra weight, but does it work? Keeping weight off permanently is very different from following the latest fad  crash diet. Trying to follow something which doesn't really fit into your life is hard to stick with, and weight gain can often happen later when the diet is inevitably broken.
</p>
<p>
  Our day to day life is made up of many habits. The key to successful weight loss that lasts is changing these habits by developing the right skills and strategies to deal with them.
</p>
<p>
  Managing our weight is a challenge and many factors can play a part in our success. We can help you understand all aspects of your weight management and sort the facts from the fiction about what will work. Together, you can look at all the issues involved and come up with a way forward that works for you.
</p>

