<h1>
Weight Loss
</h1>
<p>
Slimming diets are ever-popular, but do they really work? Sometimes yes they do, however keeping weight off permanently requires work and dedication. Following a weight loss diet that doesn't accurately match your needs is difficult. It can also be ineffective, as weight can return as willpower wanes.
</p>
<p>
Our daily diet is often habitual and based on learned behaviours. Successful and permanent weight loss may mean changing these behaviours, and simultaneously developing skills and strategies to deal with them.
</p>
<p>
Managing weight loss is a challenge and many factors can help or hinder us, even when we have the best intentions. South East Nutrition and Health can help you understand all aspects of your weight management and help you achieve your goals, and maintain your personal healthy, ideal weight.
</p>

