<h1>
Your Organisation
</h1>
<p>
The dietary needs of your employees or colleagues are often overlooked, and as an employer or manager responsible for providing catering for staff you should consider the nutritional effects of your choices (or lack of them!) ...
</p>
<p>
We can help you to create a sound nutritional basis for the provision of catering and nutrition within your organisation...
</p>
<p>
South East nutrition can offer a range of services for the organisation whether it be focused on the individual employee or to the interpretation and implementation of the government public sector food procurement initiative (PSFPI) 
</p>
<p>
Assistance in implementing national nutritional standards in schools and nurseries and other organisations ensuring current legislation is being complied with. 
</p>


