<h1>
Your Health
</h1>
<p>
South East Nutrition and Health can help with diet in many ways, however it may be the case that you have one or more particular medical conditions that are related to your diet.
</p>
<p>
There are several diseases and conditions that have specific diet-related causes or symptoms. These include type 2 diabetes, irritable bowel syndrome and coeliac disease for example. There are many other conditions that are affected by diet over time, such as heart disease. And there are some conditions such as allergies that are manageable through testing and avoidance of certain trigger foods.
</p>
