<h1>
Your Organisation
</h1>
<p>
The dietary needs of your employees or colleagues are often overlooked, and as an employer or manager responsible for providing catering for staff you should consider the nutritional effects of your choices (or lack of them!) ...
</p>
<p>
There are many positive benefits to be gained from good quality nutrition in organisations: improved morale, motivation and productivity to name but three.
</p>
<p>
We can help you to create a sound nutritional basis for the provision of catering and nutrition within your organisation...
</p>
<p>
South East nutrition can offer dietetic services for organisations whether for individual employees or for the implementation of the government's public sector food procurement initiative (PSFPI.) 
</p>
<p>
Assistance in implementing national nutritional standards in schools and nurseries and other organisations ensuring current legislation is being complied with. 
</p>


